version: '3.9'
services:
  app:
    build: .
    container_name: menu
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: menu_db
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
