version: '3.9'
services:
  app:
    build: .
    container_name: menu
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - ylab_network
    depends_on:
      postgres_ylab:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    profiles: ["app"]

  app-test:
    build: .
    container_name: menu_test
    env_file:
      - ./test.env
    networks:
      - ylab_network
    depends_on:
      postgres_ylab:
        condition: service_healthy
    profiles: ["tests"]
    command: "poetry run pytest ./tests -vv"

  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ylab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "ylab"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    profiles: ["tests", "app"]

networks:
  ylab_network:
    name: ylab_network
