version: '3.9'
services:
  app:
    build: .
    container_name: menu
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
    networks:
      - ylab_network
    depends_on:
      redis:
        condition: service_started
      postgres_ylab:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    profiles: ["app"]

  app-test:
    build: .
    container_name: menu_test
    env_file:
      - ./test.env
    networks:
      - ylab_network
    depends_on:
      postgres_ylab:
        condition: service_healthy
    profiles: ["tests"]
    command: "poetry run pytest ./tests -vv"

  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: "${POSTGRES_DB}, ${POSTGRES_DB_TEST}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s
    profiles: ["tests", "app"]

  redis:
    container_name: redis_ylab
    image: redislabs/rejson:2.2.0
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ylab_network
    env_file:
      - ./.env
    profiles: ["tests", "app"]

  worker:
    build: .
    container_name: worker_ylab
    restart: always
    env_file:
      - ./.env
    command: celery -A app.celery.tasks worker --loglevel=info
    depends_on:
      - app
      - rabbitmq
    networks:
      - ylab_network
    profiles: ["app"]

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ylab_network
    profiles: ["app"]

  # dashboard:
  #   build: .
  #   command: celery -A app.celery.tasks flower --port=5555
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  #   depends_on:
  #     - app
  #     - rabbitmq
  #     - worker
  #   networks:
  #     - ylab_network

networks:
  ylab_network:
    name: ylab_network

volumes:
  redis_data:
  postgres_data:
